language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
install:
    - vim --version
    - pip install coveralls
script:
    - coverage run --source=headlessvim setup.py test
after_success:
    - coveralls
