language: python
python:
    - 2.7
env:
    matrix:
        - TOXENV=py26
        - TOXENV=py27
        - TOXENV=py32
        - TOXENV=py33
        - TOXENV=py34
        - TOXENV=coveralls
        - TOXENV=flake8
        - TOXENV=isort
        - TOXENV=sphinx
install:
    - vim --version
    - pip install tox
script:
    - tox
